# Generated by Django 4.2 on 2023-07-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='الصنف')),
            ],
            options={
                'verbose_name_plural': 'الأصناف',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.BooleanField(blank=True, null=True, verbose_name='عليه خسم'),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='وصف المنتج'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(verbose_name='السعر بعد الخسم'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
    ]
